### ISSUE TITLE
switch as_data_frame() to as_tibble()

### ISSUE THREAD

**Issue by jrosen48** [bretsw/tidytags#20]
```
In addition: Warning message:
`as_data_frame()` is deprecated as of tibble 2.0.0.
```

**Comment by bretsw** [comment]
Where did you hit this warning? I think the issue is with a package we import, not with tidytags code

**Comment by bretsw** [comment]
I think this comes when using `get_url_domain()`, and I believe the warning originates from `longurl::expand_urls()`

**Comment by jrosen48** [comment]
can we wrap `longurl::expand_urls()` in `suppressWarnings()`?
