### ISSUE TITLE
alternative to Google Maps geocoding

### ISSUE THREAD

**Issue by maelle** [bretsw/tidytags#26]
Outside of my role as editor, let me introduce you to [opencage](https://docs.ropensci.org/opencage), where a lot of work by @dpprdan is happening in the dev branch these days. Not sure you even need an alternative to Google maps. :wink:

**Comment by maelle** [comment]
Two advantages

* no "billing account" for free accounts
* use of open data so you're allowed to keep it.

**Comment by bretsw** [comment]
I have switched geocode_tags() to draw from OpenCage API instead of Google Maps API. The geocode_tags() documentation has been updated, and the setup.Rmd and tidytags-with-conf-hashtags.Rmd vignettes have been adjusted as well.

**Comment by maelle** [comment]
@bretsw cool! have you noticed opencage default branch got a huge update?

**Comment by bretsw** [comment]
Ooo I didn't look that closely, I was just happy that I got everything working. I'll go back and give better attention. Thank you for pointing this out—I'm really excited by the functionality, open data, and pricing of OpenCage!
