### ISSUE TITLE
read_tags error

### ISSUE THREAD

**Issue by meteakca** [bretsw/tidytags#3]
I made sure my [TAGS](https://docs.google.com/spreadsheets/d/1QKv0vkYsZV2h2fLBCEaNLX2Yod6qBPUeAyPFctQlAOg/edit#gid=8743918) file is set to public, but I still get an error when I try the read_tags() function:

Tried the example URL and it works, fww.
```
Sheet-identifying info appears to be a browser URL.
googlesheets will attempt to extract sheet key from the URL.
Putative key: 1QKv0vkYsZV2h2fLBCEaNLX2Yod6qBPUeAyPFctQlAOg
Worksheets feed constructed with public visibility
Error in stop_for_content_type(req, expected = "application/atom+xml; charset=UTF-8") : 
  Expected content-type:
application/atom+xml; charset=UTF-8
Actual content-type:
text/html; charset=UTF-8
```

**Comment by meteakca** [comment]
file needs to be published to the web first. Thanks @bretsw!

**Comment by jrosen48** [comment]
Good to know! thanks.
