### ISSUE TITLE
Twitter token in vcr cassettes

### ISSUE THREAD

**Issue by maelle** [bretsw/tidytags#30]
When you use Twitter API the secret is not the path to the Twitter httr token (what's in the "secret" `TWITTER_PAT` environment variable) but inside the token file.

In such a case you need to use https://books.ropensci.org/http-testing/vcr-security.html#if-the-secret-is-in-a-request-header

* Please change your vcr configuration
* Please invalidate your token that has been leaked. Probably via de-authorizing the Twitter app you created for getting the token.

**Comment by maelle** [comment]
@bretsw

**Comment by maelle** [comment]
note that the access token leaked was maybe already invalid (as such tokens are refreshed regularly, but I prefer to be on the safe side)

**Comment by bretsw** [comment]
Thank you for catching this. I've revoked the leaked tokens and generated new ones.

**Comment by maelle** [comment]
Please check things work ok next time you record the vcr cassettes. (I wouldn't trust the config tweak I PR-ed if you don't try it :-) )
