### ISSUE TITLE
some notes

### ISSUE THREAD

**Issue by maelle** [bretsw/tidytags#33]
* opencage itself was having vcr tests problem due to memoise but memoise has been released on CRAN cc @dpprdan so I think the issue with the failing test might be something related to the sensitive data filtering?

* reg rtweet that's on Windows only, not sure yet why the token can't be found.

**Comment by maelle** [comment]
maybe `vcr::vcr_test_path("fixtures")` doesn't work well on Windows? cc @sckott

**Comment by sckott** [comment]
what exactly is the problem?

**Comment by maelle** [comment]
on Windows the rtweet token created in setup-tidytags.R (a fake token needed for tests without secrets available) isn't found whereas on Ubuntu it is found and the rtweet-related tests pass.

**Comment by sckott** [comment]
okay, can you replicate this on your own windows machine? or only on windows CI?

**Comment by sckott** [comment]
@maelle where is the evidence that makes you think `vcr_test_path` is to blame here?

**Comment by maelle** [comment]
No evidence, i was just gathering ideas

**Comment by maelle** [comment]
It was on CI

**Comment by sckott** [comment]
i've not used `vcr_test_path` so I'm not super familiar with it - i don't know why, though it doesn't work with `devtools::test()` which is how I run tests locally (via a make command) 

checked `vcr_test_path` on windows GH Actions CI with `rplos` - and it seems to work https://github.com/ropensci/rplos/runs/1825458162 on windows

**Comment by maelle** [comment]
ok so the problem must lie elsewhere.

The other unrelated bug we observed, that seems more serious, is https://github.com/ropensci/vcr/issues/221

**Comment by maelle** [comment]
@bretsw actually were some of the rtweet tests outside of cassettes? Did you make some progress on this?

**Comment by maelle** [comment]
ah no the failing tests _are_ inside cassettes.

**Comment by maelle** [comment]
now the other builds are successful (the ones not on Windows), what was changed @bretsw ?

**Comment by bretsw** [comment]
> now the other builds are successful (the ones not on Windows), what was changed @bretsw ?

@maelle The only thing I changed prior to those successful builds (minus Windows) was to completely clear out my GitHub Actions secrets. So it seems like however I had stored the OpenCage token in there must have been problematic.

**Comment by bretsw** [comment]
So it seems like the remaining issue is related to rtweet tokens on Windows only

**Comment by maelle** [comment]
so weird and interesting. did your secret have ' or " in it? because if that's the case I definitely want to add it as a gotcha in the HTTP testing book!

**Comment by bretsw** [comment]
It was stored with "

`OPENCAGE_KEY="11a1111a111a1a1a1a111111a1aa11a1"`

because that follows how keys are saved in my local .Renviron file. Any clarity you can add in the book on that regard would be appreciated!

**Comment by bretsw** [comment]
(hopefully it's obvious that `11a1111a111a1a1a1a111111a1aa11a1` is a fake key

**Comment by maelle** [comment]
ahah yes it is :grin: 

I think what is BAD is

![image](https://user-images.githubusercontent.com/8360597/106887317-49679080-66e5-11eb-8abb-5f18a6ad1106.png)

What is GOOD is

![image](https://user-images.githubusercontent.com/8360597/106887351-54222580-66e5-11eb-91d0-71d8f763d7db.png)

**Comment by bretsw** [comment]
Perfect! Thanks for screenshots! So helpful :)

**Comment by bretsw** [comment]
> on Windows the rtweet token created in setup-tidytags.R (a fake token needed for tests without secrets available) isn't found whereas on Ubuntu it is found and the rtweet-related tests pass.

@maelle any new ideas on this one? I'm really at a loss re: why the build works on Mac and Ubuntu but fail on Windows. Something weird is going on with that rtweet token

**Comment by maelle** [comment]
I don't have any good guess at the moment. :thinking:

**Comment by bretsw** [comment]
> on Windows the rtweet token created in setup-tidytags.R (a fake token needed for tests without secrets available) isn't found whereas on Ubuntu it is found and the rtweet-related tests pass.

@maelle, as I look at the error log, the Windows build fails at `rtweet:::rstats2twitter_client()`. When I look at this function in rtweet (https://github.com/ropensci/rtweet/search?q=rstats2twitter_client), I see in **tokens.R** (lines 570-584):

```{r}
rstats2twitter_client <- function() {
  if (!interactive()) {
    stop("API user token required. see http://rtweet.info/articles/auth.html for instructions",
      call. = FALSE)
  }
...
```

Again, I don't know why `interactive()` is triggering something in the Windows build that's not elsewhere, but it seems like the failure to build is somewhere in this realm.

Gargle seems to address the issue of non-interactivity:
https://cran.r-project.org/web/packages/gargle/vignettes/non-interactive-auth.html

rtweet saves Twitter tokens to an .rds file, so perhaps running `readRDS(".rtweet_token.rds")` manually would retrieve the file created by `rtweet::create_token()` in tidytags?

I feel like I'm a bit out of my depth here, and maybe you've worked through all these possibilities already. I'm hoping there's something in here that helps, though.

**Comment by sckott** [comment]
I'm not sure what exactly is going on, but I'll have a look

**Comment by bretsw** [comment]
Thank you!

**Comment by sckott** [comment]
If I were you I'd maybe make a git branch, remove all tests except for the ones that use rtweet, and just test on windows, and add `VCR_TURN_OFF: true` to your gh actions config file which will ignore vcr and do real http requests (assuming that's okay to do on CI?, I don't know if it is or not) - then you can see if it's an issue that involves vcr or not - I don't think it does but may be wrong

**Comment by bretsw** [comment]
I'll give this a shot this weekend/early next week. Thanks!
