### ISSUE TITLE
pull this for geocoding together into a function?

### ISSUE THREAD

**Issue by jrosen48** [bretsw/tidytags#8]
```
example_unique_places <- dplyr::distinct(geocoded_locs, location, .keep_all = TRUE)
example_geo_coords <- geocode_tags(example_unique_places)
example_map <- mapview::mapview(example_geo_coords$pnt) 
```

**Comment by bretsw** [comment]
make into one function: plot_geo_codes()

**Comment by jrosen48** [comment]
is this addressed in https://github.com/bretsw/tidytags/commit/602c52e68c40c48e188968bbffffcd5aa4de615a?

**Comment by bretsw** [comment]
I read your original comment as wanting a new function, perhaps named `plot_geo_codes()`. This function has not yet been created.

**Comment by jrosen48** [comment]
after starting tow work on this, I think it's okay to keep this separate - it's effectively just to functions, `geocode_tags()` and then `mapview()`.

I will instead make some small changes to the vignette to make this even more clear.

**Comment by bretsw** [comment]
Perfect, sounds good. Make same changes in the `geocode_tags()` documentation too?

**Comment by jrosen48** [comment]
yep will do

________________________________________
